# Generated by Django 4.1.5 on 2023-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVIN_main', '0002_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
