# Generated by Django 4.1.5 on 2023-02-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVIN_main', '0005_alter_votes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='author',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
